---
### Fedora 28
- name: Fedora 28 BIOS
  command: >-
    fast-vm import_image fedora28 {{ public_image_url_base }}/generated/6g__fedora-28.img.xz
    {{ xml_url_base }}/fedora/xml/fedora-28-current.xml
    {{ hacks_url_base }}/fedora/hacks/6g_fedora-28-hacks.sh
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}fedora28"
  tags:
    - fedora
    - fedora_28

### Fedora 29
- name: Fedora 29 BIOS
  command: >-
    fast-vm import_image fedora29 {{ public_image_url_base }}/generated/6g__fedora-29.img.xz
    {{ xml_url_base }}/fedora/xml/fedora-28-current.xml
    {{ hacks_url_base }}/fedora/hacks/6g_fedora-29-hacks.sh
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}fedora29"
  tags:
    - fedora
    - fedora_29

### Fedora 30
- name: Fedora 30 BIOS
  command: >-
    fast-vm import_image fedora30 {{ public_image_url_base }}/generated/6g__fedora-30.img.xz
    {{ xml_url_base }}/fedora/xml/fedora-28-current.xml
    {{ hacks_url_base }}/fedora/hacks/6g_fedora-30-hacks.sh
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}fedora30"
  tags:
    - fedora
    - fedora_30

### Fedora 31
- name: Fedora 31 BIOS
  command: >-
    fast-vm import_image fedora31 {{ public_image_url_base }}/generated/6g__fedora-31.img.xz
    {{ xml_url_base }}/fedora/xml/fedora-28-current.xml
    {{ hacks_url_base }}/fedora/hacks/6g_fedora-31-hacks.sh
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}fedora31"
  tags:
    - fedora
    - fedora_31
