---
- name: create directory for ansible custom facts
  file: state=directory recurse=yes path=/etc/ansible/facts.d
  tags: always

- name: generate fast-vm custom facts
  shell: echo '[conf]' > /etc/ansible/facts.d/fastvm.fact && cat /etc/fast-vm.conf >> /etc/ansible/facts.d/fastvm.fact
  tags: always

- name: re-read facts after adding custom fact
  setup: filter=ansible_local
  tags: always

- name: Check the presence of fast-vm variables after facts were generated
  fail: msg="variable {{ item }} is not defined, is the fast-vm installation working on that machine?"
  when: item is not defined
  with_items:
    - ansible_local.fastvm.conf.thinpool_vg
    - ansible_local.fastvm.conf.vm_prefix
  tags: always

####
- name: include centos6 images
  include: centos6.yml
  tags:
    - centos
    - centos6_all
- name: include centos7 images
  include: centos7.yml
  tags:
    - centos
    - centos7_all
- name: include fedora images
  include: fedora.yml
- name: include ubuntu images
  include: ubuntu.yml
- name: include debian images
  include: debian.yml
- name: include rhel5 images
  include: rhel5.yml
  when: rhel_image_url_base|length > 0
  tags:
    - rhel
    - rhel5_all
- name: include rhel6 images
  include: rhel6.yml
  when: rhel_image_url_base|length > 0
  tags:
    - rhel
    - rhel6_all
- name: include rhel7 images
  include: rhel7.yml
  when: rhel_image_url_base|length > 0
  tags:
    - rhel
    - rhel7_all
- name: include rhel8 images
  include: rhel8.yml
  when: rhel_image_url_base|length > 0
  tags:
    - rhel
    - rhel8_all
