---
### import Fedora 29 appliance on CentOS/RHEL systems
- name: create /var/tmp/fedora29 direcotry for libguestfs appliance
  file:
    path: '/var/tmp/fedora29'
    state: 'directory'
  when: ansible_distribution != 'Fedora'

- name: download and unpack the Fedora 29 appliance
  unarchive:
    src: 'http://ftp.linux.cz/pub/linux/people/ondrej_famera/fastvm-images/appliance-1.39.11.tar.xz'
    dest: '/var/tmp/fedora29'
    remote_src: yes
  when: ansible_distribution != 'Fedora'

### RHEL 8.0 Beta
- name: RHEL 8.0 BIOS
  shell: "fast-vm import_image rhel-8.0-beta {{ rhel_image_url_base }}/generated/6g__rhel-8.0-beta.img.xz {{ xml_url_base }}/rhel/xml/rhel-6.3-current.xml {{ hacks_url_base }}/rhel/hacks/6g_rhel-8-hacks.sh"
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}rhel-8.0-beta"
  tags:
    - rhel8_beta
    - rhel8_0_beta

- name: RHEL 8.0 UEFI
  shell: "fast-vm import_image rhel-8.0-beta-uefi {{ rhel_image_url_base }}/generated/6g__rhel-8.0-uefi-uefi.img.xz {{ xml_url_base }}/rhel/xml/rhel-7.0-current-uefi.xml {{ hacks_url_base }}/rhel/hacks/6g_rhel-8-hacks-uefi.sh"
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}rhel-8.0-beta-uefi"
  tags:
    - rhel8_beta_uefi
    - rhel8_0_beta_uefi

