---
### RHEL 7.0
- name: RHEL 7.0 BIOS
  shell: "fast-vm import_image rhel-7.0 {{ rhel_image_url_base }}/generated/6g__rhel-7.0.img.xz {{ xml_url_base }}/rhel/xml/rhel-6.3-current.xml {{ hacks_url_base }}/rhel/hacks/6g_rhel-7-hacks.sh"
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}rhel-7.0"
  tags:
    - rhel7
    - rhel7_0

- name: RHEL 7.0 UEFI
  shell: "fast-vm import_image rhel-7.0-uefi {{ rhel_image_url_base }}/generated/6g__rhel-6.3-uefi.img.xz {{ xml_url_base }}/rhel/xml/rhel-7.0-current-uefi.xml {{ hacks_url_base }}/rhel/hacks/6g_rhel-7-hacks-uefi.sh"
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}rhel-7.0-uefi"
  tags:
    - rhel7_uefi
    - rhel7_0_uefi

### RHEL 7.1
- name: RHEL 7.1 BIOS
  shell: "fast-vm import_image rhel-7.1 {{ rhel_image_url_base }}/generated/6g__rhel-7.1.img.xz {{ xml_url_base }}/rhel/xml/rhel-6.3-current.xml {{ hacks_url_base }}/rhel/hacks/6g_rhel-7-hacks.sh"
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}rhel-7.1"
  tags:
    - rhel7
    - rhel7_1

- name: RHEL 7.1 UEFI
  shell: "fast-vm import_image rhel-7.1-uefi {{ rhel_image_url_base }}/generated/6g__rhel-6.3-uefi.img.xz {{ xml_url_base }}/rhel/xml/rhel-7.0-current-uefi.xml {{ hacks_url_base }}/rhel/hacks/6g_rhel-7-hacks-uefi.sh"
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}rhel-7.1-uefi"
  tags:
    - rhel7_uefi
    - rhel7_1_uefi

### RHEL 7.2
- name: RHEL 7.2 BIOS
  shell: "fast-vm import_image rhel-7.2 {{ rhel_image_url_base }}/generated/6g__rhel-7.2.img.xz {{ xml_url_base }}/rhel/xml/rhel-6.3-current.xml {{ hacks_url_base }}/rhel/hacks/6g_rhel-7-hacks.sh"
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}rhel-7.2"
  tags:
    - rhel7
    - rhel7_2

- name: RHEL 7.2 UEFI
  shell: "fast-vm import_image rhel-7.2-uefi {{ rhel_image_url_base }}/generated/6g__rhel-6.3-uefi.img.xz {{ xml_url_base }}/rhel/xml/rhel-7.0-current-uefi.xml {{ hacks_url_base }}/rhel/hacks/6g_rhel-7-hacks-uefi.sh"
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}rhel-7.2-uefi"
  tags:
    - rhel7_uefi
    - rhel7_2_uefi

### RHEL 7.3
- name: RHEL 7.3 BIOS
  shell: "fast-vm import_image rhel-7.3 {{ rhel_image_url_base }}/generated/6g__rhel-7.3.img.xz {{ xml_url_base }}/rhel/xml/rhel-6.3-current.xml {{ hacks_url_base }}/rhel/hacks/6g_rhel-7-hacks.sh"
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}rhel-7.3"
  tags:
    - rhel7
    - rhel7_3

- name: RHEL 7.3 UEFI
  shell: "fast-vm import_image rhel-7.3-uefi {{ rhel_image_url_base }}/generated/6g__rhel-6.3-uefi.img.xz {{ xml_url_base }}/rhel/xml/rhel-7.0-current-uefi.xml {{ hacks_url_base }}/rhel/hacks/6g_rhel-7-hacks-uefi.sh"
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}rhel-7.3-uefi"
  tags:
    - rhel7_uefi
    - rhel7_3_uefi

### RHEL 7.4
- name: RHEL 7.4 BIOS
  shell: "fast-vm import_image rhel-7.4 {{ rhel_image_url_base }}/generated/6g__rhel-7.4.img.xz {{ xml_url_base }}/rhel/xml/rhel-6.3-current.xml {{ hacks_url_base }}/rhel/hacks/6g_rhel-7-hacks.sh"
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}rhel-7.4"
  tags:
    - rhel7
    - rhel7_4

- name: RHEL 7.4 UEFI
  shell: "fast-vm import_image rhel-7.4-uefi {{ rhel_image_url_base }}/generated/6g__rhel-6.3-uefi.img.xz {{ xml_url_base }}/rhel/xml/rhel-7.0-current-uefi.xml {{ hacks_url_base }}/rhel/hacks/6g_rhel-7-hacks-uefi.sh"
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}rhel-7.4-uefi"
  tags:
    - rhel7_uefi
    - rhel7_4_uefi

### RHEL 7.5
- name: RHEL 7.5 BIOS
  shell: "fast-vm import_image rhel-7.5 {{ rhel_image_url_base }}/generated/6g__rhel-7.5.img.xz {{ xml_url_base }}/rhel/xml/rhel-6.3-current.xml {{ hacks_url_base }}/rhel/hacks/6g_rhel-7-hacks.sh"
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}rhel-7.5"
  tags:
    - rhel7
    - rhel7_5

- name: RHEL 7.5 UEFI
  shell: "fast-vm import_image rhel-7.5-uefi {{ rhel_image_url_base }}/generated/6g__rhel-7.5-uefi.img.xz {{ xml_url_base }}/rhel/xml/rhel-7.0-current-uefi.xml {{ hacks_url_base }}/rhel/hacks/6g_rhel-7-hacks-uefi.sh"
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}rhel-7.5-uefi"
  tags:
    - rhel7_uefi
    - rhel7_5_uefi

### RHEL 7.6
- name: RHEL 7.6 BIOS
  shell: "fast-vm import_image rhel-7.6 {{ rhel_image_url_base }}/generated/6g__rhel-7.6.img.xz {{ xml_url_base }}/rhel/xml/rhel-6.3-current.xml {{ hacks_url_base }}/rhel/hacks/6g_rhel-7-hacks.sh"
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}rhel-7.6"
  tags:
    - rhel7
    - rhel7_6

- name: RHEL 7.6 UEFI
  shell: "fast-vm import_image rhel-7.6-uefi {{ rhel_image_url_base }}/generated/6g__rhel-7.6-uefi.img.xz {{ xml_url_base }}/rhel/xml/rhel-7.0-current-uefi.xml {{ hacks_url_base }}/rhel/hacks/6g_rhel-7-hacks-uefi.sh"
  args:
    creates: "/dev/{{ ansible_local.fastvm.conf.thinpool_vg }}/{{ ansible_local.fastvm.conf.vm_prefix }}rhel-7.6-uefi"
  tags:
    - rhel7_uefi
    - rhel7_6_uefi
